config/routes.rb
Rails.application.routes.draw do
  resources :temps
  resources :phs

   root 'temps#index'

end

app/models/ph.rb
class Ph < ActiveRecord::Base
end

app/models/temp.rb
class Temp < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/phs_controller.rb
class PhsController < ApplicationController
  before_action :set_ph, only: [:show, :edit, :update, :destroy]

  # GET /phs
  # GET /phs.json
  def index
    @phs = Ph.all
  end

  # GET /phs/1
  # GET /phs/1.json
  def show
  end

  # GET /phs/new
  def new
    @ph = Ph.new
  end

  # GET /phs/1/edit
  def edit
  end

  # POST /phs
  # POST /phs.json
  def create
    @ph = Ph.new(ph_params)

    respond_to do |format|
      if @ph.save
        format.html { redirect_to @ph, notice: 'Ph was successfully created.' }
        format.json { render :show, status: :created, location: @ph }
      else
        format.html { render :new }
        format.json { render json: @ph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phs/1
  # PATCH/PUT /phs/1.json
  def update
    respond_to do |format|
      if @ph.update(ph_params)
        format.html { redirect_to @ph, notice: 'Ph was successfully updated.' }
        format.json { render :show, status: :ok, location: @ph }
      else
        format.html { render :edit }
        format.json { render json: @ph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phs/1
  # DELETE /phs/1.json
  def destroy
    @ph.destroy
    respond_to do |format|
      format.html { redirect_to phs_url, notice: 'Ph was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ph
      @ph = Ph.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ph_params
      params[:ph]
    end
end

app/controllers/temps_controller.rb
class TempsController < ApplicationController
  before_action :set_temp, only: [:show, :edit, :update, :destroy]

  # GET /temps
  # GET /temps.json
  def index
    @temps = Temp.all
  end

  # GET /temps/1
  # GET /temps/1.json
  def show
  end

  # GET /temps/new
  def new
    @temp = Temp.new
  end

  # GET /temps/1/edit
  def edit
  end

  # POST /temps
  # POST /temps.json
  def create
    @temp = Temp.new(temp_params)

    respond_to do |format|
      if @temp.save
        format.html { redirect_to @temp, notice: 'Temp was successfully created.' }
        format.json { render :show, status: :created, location: @temp }
      else
        format.html { render :new }
        format.json { render json: @temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temps/1
  # PATCH/PUT /temps/1.json
  def update
    respond_to do |format|
      if @temp.update(temp_params)
        format.html { redirect_to @temp, notice: 'Temp was successfully updated.' }
        format.json { render :show, status: :ok, location: @temp }
      else
        format.html { render :edit }
        format.json { render json: @temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temps/1
  # DELETE /temps/1.json
  def destroy
    @temp.destroy
    respond_to do |format|
      format.html { redirect_to temps_url, notice: 'Temp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_temp
      @temp = Temp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def temp_params
      params[:temp]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phs_helper.rb
module PhsHelper
end

app/helpers/temps_helper.rb
module TempsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fish</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/phs/_form.html.erb
<%= form_for(@ph) do |f| %>
  <% if @ph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ph.errors.count, "error") %> prohibited this ph from being saved:</h2>

      <ul>
      <% @ph.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phs/edit.html.erb
<h1>Editing Ph</h1>

<%= render 'form' %>

<%= link_to 'Show', @ph %> |
<%= link_to 'Back', phs_path %>

app/views/phs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Phs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phs.each do |ph| %>
      <tr>
        <td><%= link_to 'Show', ph %></td>
        <td><%= link_to 'Edit', edit_ph_path(ph) %></td>
        <td><%= link_to 'Destroy', ph, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ph', new_ph_path %>

app/views/phs/new.html.erb
<h1>New Ph</h1>

<%= render 'form' %>

<%= link_to 'Back', phs_path %>

app/views/phs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ph_path(@ph) %> |
<%= link_to 'Back', phs_path %>

app/views/temps/_form.html.erb
<%= form_for(@temp) do |f| %>
  <% if @temp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@temp.errors.count, "error") %> prohibited this temp from being saved:</h2>

      <ul>
      <% @temp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/temps/edit.html.erb
<h1>Editing Temp</h1>

<%= render 'form' %>

<%= link_to 'Show', @temp %> |
<%= link_to 'Back', temps_path %>

app/views/temps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Temps</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temps.each do |temp| %>
      <tr>
        <td><%= link_to 'Show', temp %></td>
        <td><%= link_to 'Edit', edit_temp_path(temp) %></td>
        <td><%= link_to 'Destroy', temp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Temp', new_temp_path %>

app/views/temps/new.html.erb
<h1>New Temp</h1>

<%= render 'form' %>

<%= link_to 'Back', temps_path %>

app/views/temps/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_temp_path(@temp) %> |
<%= link_to 'Back', temps_path %>